In [1]:
import numpy as np

In [2]:
arr1=np.array([2,11,3,5,33,89,23,54,87,86,75,34,78,35,2,4,77,2,87,2,5,87,89,2])
arr1

array([ 2, 11,  3,  5, 33, 89, 23, 54, 87, 86, 75, 34, 78, 35,  2,  4, 77,
        2, 87,  2,  5, 87, 89,  2])

In [3]:
arr1.max()

89

In [4]:
arr1.min()

2

In [5]:
arr1.argmax() #gives index of max element of array

5

In [6]:
arr1.argmin()

0

In [7]:
np.log(arr1)

array([0.69314718, 2.39789527, 1.09861229, 1.60943791, 3.49650756,
       4.48863637, 3.13549422, 3.98898405, 4.46590812, 4.4543473 ,
       4.31748811, 3.52636052, 4.35670883, 3.55534806, 0.69314718,
       1.38629436, 4.34380542, 0.69314718, 4.46590812, 0.69314718,
       1.60943791, 4.46590812, 4.48863637, 0.69314718])

In [8]:
np.sin(arr1)

array([ 0.90929743, -0.99999021,  0.14112001, -0.95892427,  0.99991186,
        0.86006941, -0.8462204 , -0.55878905, -0.82181784, -0.92345845,
       -0.38778164,  0.52908269,  0.51397846, -0.42818267,  0.90929743,
       -0.7568025 ,  0.99952016,  0.90929743, -0.82181784,  0.90929743,
       -0.95892427, -0.82181784,  0.86006941,  0.90929743])

In [9]:
np.exp(arr1)

array([7.38905610e+00, 5.98741417e+04, 2.00855369e+01, 1.48413159e+02,
       2.14643580e+14, 4.48961282e+38, 9.74480345e+09, 2.83075330e+23,
       6.07603023e+37, 2.23524660e+37, 3.73324200e+32, 5.83461743e+14,
       7.49841700e+33, 1.58601345e+15, 7.38905610e+00, 5.45981500e+01,
       2.75851345e+33, 7.38905610e+00, 6.07603023e+37, 7.38905610e+00,
       1.48413159e+02, 6.07603023e+37, 4.48961282e+38, 7.38905610e+00])

In [10]:
np.std(arr1) #gives standard deviation of array

36.14092786117516

In [11]:
np.mean(arr1)

40.5

In [12]:
np.var(arr1) # gives variance of array

1306.1666666666667

In [13]:
arr1[1:6]

array([11,  3,  5, 33, 89])

In [14]:
list=[6,23,12,75,44,33,21]
arr2=np.array(list)
arr2

array([ 6, 23, 12, 75, 44, 33, 21])

In [15]:
arr3=np.arange(4,15)
arr3

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
arr4=np.arange(1,100,8)
arr4

array([ 1,  9, 17, 25, 33, 41, 49, 57, 65, 73, 81, 89, 97])

In [17]:
arr5=np.zeros(7,int)
arr5

array([0, 0, 0, 0, 0, 0, 0])

In [18]:
arr6=np.ones(9,float)
arr6

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
arr7=np.eye(5,dtype=int)
arr7

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [20]:
arr8=np.linspace(7,80,10)
arr8

array([ 7.        , 15.11111111, 23.22222222, 31.33333333, 39.44444444,
       47.55555556, 55.66666667, 63.77777778, 71.88888889, 80.        ])

In [21]:
arr9=np.random.rand(3,5)
arr9

array([[0.06472258, 0.37535264, 0.62516439, 0.47546155, 0.9405816 ],
       [0.56367535, 0.62895854, 0.88351674, 0.67121031, 0.1506282 ],
       [0.52906472, 0.46295505, 0.30934267, 0.29273248, 0.68818882]])

In [22]:
arr9.round(4)

array([[0.0647, 0.3754, 0.6252, 0.4755, 0.9406],
       [0.5637, 0.629 , 0.8835, 0.6712, 0.1506],
       [0.5291, 0.463 , 0.3093, 0.2927, 0.6882]])

In [23]:
arr10=np.random.randn(4,4)
arr10

array([[-0.25584185,  1.07598127, -0.96466347,  0.62043946],
       [-0.78769097, -1.20808561, -1.93007212, -0.37851264],
       [ 0.26998134, -1.72261455,  0.5427151 , -0.39132689],
       [ 0.7858164 ,  0.59202168,  0.47951919, -0.29987449]])

In [24]:
arr11=np.random.randint(1,100) 
arr11

17

In [25]:
arr12=np.arange(2,20)
arr12

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [26]:
arr13=np.reshape(arr12,(3,6))
arr13

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19]])

In [27]:
arr13.size

18

In [28]:
arr13.shape

(3, 6)

In [29]:
arr13.ravel()

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [30]:
arr14=arr13.T #for matrix transpose
arr14

array([[ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17],
       [ 6, 12, 18],
       [ 7, 13, 19]])

In [31]:
arr14[3]=100
arr14

array([[  2,   8,  14],
       [  3,   9,  15],
       [  4,  10,  16],
       [100, 100, 100],
       [  6,  12,  18],
       [  7,  13,  19]])

In [32]:
arr14[:,:2]

array([[  2,   8],
       [  3,   9],
       [  4,  10],
       [100, 100],
       [  6,  12],
       [  7,  13]])

In [33]:
arr14[2:5,:]

array([[  4,  10,  16],
       [100, 100, 100],
       [  6,  12,  18]])

In [34]:
arr14+arr14

array([[  4,  16,  28],
       [  6,  18,  30],
       [  8,  20,  32],
       [200, 200, 200],
       [ 12,  24,  36],
       [ 14,  26,  38]])